### ISSUE TITLE
Broken link in Articles, blogs etc

### ISSUE THREAD

**Issue by WolfgangPires** [valignatev/ddd-dynamic#12]
https://stevewedig.com/2014/07/31/value-objects-in-java-and-python/

**Comment by valignatev** [comment]
Hi @WolfgangPires, thanks a lot for pointing out! I've fixed it in https://github.com/valignatev/ddd-dynamic/commit/26923da6eff5b60b7a538167eb800540f72b7346. Now the link points to the version from web.archive.org
