### ISSUE TITLE
Adding another example of DDD in python

### ISSUE THREAD

**Issue by Hyaxia** [valignatev/ddd-dynamic#31]
Hi, I'm currently working on a project that uses DDD in combination with CQRS and ES.

https://github.com/Hyaxia/Bank-DDD-CQRS-ES

The domain is banking.
Was wondering if it can be added, so it will get more exposure so people see another option on how to create such applications in python and in best case scenario leave some feedback.
Thanks!

**Comment by valignatev** [comment]
Heyo! Sure, go ahead and create a pull request, I'll gladly merge it.
