### ISSUE TITLE
made.com links dead (DDD with Ports and Adapters in Python)

### ISSUE THREAD

**Issue by jdittrich** [valignatev/ddd-dynamic#37]
The io.made.com links are dead, like: [DDD with Ports and Adapters in Python](https://io.made.com/blog/2017-09-07-introducing-command-handler.html). I wonder if they all moved to https://www.cosmicpython.com/ ? At least the titles of the post seem to be the same like the "Classic 2017 Episodes on Ports & Adapters, by Bob"

**Comment by valignatev** [comment]
yeah that must be it, I'll get to updating them at some point, thanks for reporting!
